WeAreRoommies/Roomie-iOS

- Roomie/Roomie/Global/Base/BaseView.swift
- Roomie/Roomie/Global/Base/BaseViewController.swift
- Roomie/Roomie/Global/Extensions/UITextField+.swift
- Roomie/Roomie/Presentation/Map/View/FilterPeriodView.swift
- Roomie/Roomie/Presentation/Map/View/FilterPriceView.swift
- Roomie/Roomie/Presentation/Map/View/FilterRoomView.swift
- Roomie/Roomie/Presentation/Map/View/FilterSegmentedControl.swift
- Roomie/Roomie/Presentation/Map/View/MapFilterView.swift
- Roomie/Roomie/Presentation/Map/View/MapView.swift
- Roomie/Roomie/Presentation/Map/ViewController/MapFilterViewController.swift
- Roomie/Roomie/Presentation/Map/ViewController/MapViewController.swift
- Connected: #16 
- 베이스 뷰컨트롤러에 경계선 유무 로직과 화면 터치 시 키보드 내리는 제스쳐 로직을 추가하였습니다.
- 베이스 뷰컨트롤러에 타이틀 색상을 수정했습니다.
- 베이스 뷰에 배경색 설정 관련 로직을 수정하였습니다. (배경이 흰 색이라면 별도의 설정을 하지 않으셔도 됩니다!)
- 지도 뷰에 컴포넌트를 추가하고 필터 뷰와 화면 연결을 진행했습니다.
- 필터 뷰의 세그먼트 컨트롤을 구현했습니다.
| 필터 뷰 | <img src = "https://github.com/user-attachments/assets/e60645fc-b7cc-4f7a-85e3-86371a8123ad" width ="250"> | <img src = "https://github.com/user-attachments/assets/990f85bd-aaf9-4a06-b0f0-7c1a2cbb0d03" width ="250"> |
- 타이틀과 함께 경계선 유무에 대한 설정을 함께할 수 있어요.
- 경계선이 있는 설정이 디폴트이기 때문에 경계선이 있는 경우 따로 설정을 하지 않으셔도 되지만, 경계선이 없는 경우 꼭 isHidden을 true로 처리해주세요 :)
<details>
<summary>사용 예시</summary>
```swift
// 베이스 뷰 컨트롤러의 setupView 함수를 오버로드 하여
override func …
```
> [feat/#16] 필터 뷰 세그먼트 컨트롤 구현 및 베이스파일 수정

- Roomie/Roomie/Global/Components/FilterOptionButton.swift
- Roomie/Roomie/Presentation/Map/View/FilterRoomView.swift
- Roomie/Roomie/Presentation/Map/ViewController/MapFilterViewController.swift
- Roomie/Roomie/Presentation/Map/ViewModel/MapFilterViewModel.swift
- Connected: #24
- 필터 뷰에 사용되는 옵션별 버튼 컴포넌트를 제작했습니다.
- 필터 뷰 UI를 구현했습니다.
- 이후 서버 통신에 편리하도록, 버튼의 클릭여부에 따라 뷰 모델에서 해당 옵션에 대한 정보를 배열로 관리하도록 했습니다.
| 방 형태 | <img src = "https://github.com/user-attachments/assets/f879d7cc-ad9d-4510-9f54-b48b8079b41d" width ="250"> | <img src = "https://github.com/user-attachments/assets/0232e55c-e7c8-422f-96c4-a4588fe695ff" width ="250"> |
MassiveViewModel 이거 맞을까 ⋯ 더 이상의 리팩은 나중에 ㅋㅋ
> [feat/#24] 필터 뷰 방 형태 UI 구현

- Roomie/Roomie/Global/Components/DatePickerView.swift
- Roomie/Roomie/Presentation/MapFilter/View/FilterPeriodView.swift
- Roomie/Roomie/Presentation/MapFilter/ViewController/MapFilterViewController.swift
- Roomie/Roomie/Presentation/MapFilter/ViewModel/MapFilterViewModel.swift
- Connected: #31 
- 데이트피커 공통 컴포넌트를 구현했습니다.
- 필터 뷰의 계약기간 UI를 구현했습니다.
| 계약기간 | <img src = "https://github.com/user-attachments/assets/6992ca1f-4699-4d7c-a8a5-9de40e959284" width ="250"> | <img src = "https://github.com/user-attachments/assets/129820f9-42ec-405f-b436-f26acc80fdd8" width ="250"> |
다음 이슈에서 필터 뷰에 버튼 붙이고 전체적인 로직 다듬을게요!
> [feat/#31] 필터 뷰 계약기간 UI 구현

- Roomie/Roomie/Global/Components/DatePickerView.swift
- Roomie/Roomie/Global/Components/GenderButton.swift
- Roomie/Roomie/Global/Components/RoomieButton.swift
- Roomie/Roomie/Global/Components/TourTextField.swift
- Roomie/Roomie/Global/Enums/Gender.swift
- Roomie/Roomie/Presentation/Tour/View/TourUserView.swift
- Roomie/Roomie/Presentation/Tour/ViewController/TourCheckViewController.swift
- Roomie/Roomie/Presentation/Tour/ViewController/TourUserViewController.swift
- Roomie/Roomie/Presentation/Tour/ViewModel/TourViewModel.swift
- Connected: #30 
- TourUserView 플로우를 구현하였습니다.
- DatePickerView 날짜 선택 시점을 받을 수 있게 Protocol을 구현했습니다.
| TourUserView 플로우 | <img src = "https://github.com/user-attachments/assets/15c647ac-bd60-4fcb-b447-5f4c686a4850" width ="250"> | <img src = "https://github.com/user-attachments/assets/3f18d7f4-04dc-449f-80d1-5f77cd53a09b" width ="250"> |
| 연락처 유효성 검사 | <img src = "https://github.com/user-attachments/assets/1829c411-851d-4c0b-b3cd-191ad4099758" width ="250"> | <img src = "https://github.com/user-attachments/assets/286bcb28-07bb-423f-9396-d3019e6c757e" width ="250"> |
- `DatePickerView`에서 날짜가 선택된 시점을 날짜 문자열과 함께 전달합니다.
- 날짜는 `"yyyy/MM/dd"` 형식으로 전달합니다.
<details> …
> [feat/#30] TourUserView 플로우, DatePickerView Protocol 구현

- Roomie/Roomie/Presentation/MapFilter/View/MapFilterView.swift
- Roomie/Roomie/Presentation/MapFilter/ViewController/MapFilterViewController.swift
- Roomie/Roomie/Presentation/MapFilter/ViewModel/MapFilterViewModel.swift
- Connected: #35 
- 초기화 버튼과 적용하기 버튼 UI를 구현했어요.
- 버튼 로직을 구현했어요.
| 버튼 | <img src = "https://github.com/user-attachments/assets/f8c77a3d-b669-4588-bd29-643dcf7608b5" width ="250"> | <img src = "https://github.com/user-attachments/assets/c563e3fb-6ff3-444d-aaaf-989f2cdaa16e" width ="250">|
승원이가 데이트 피커 뷰에 delegate 연결을 해줘서 ㅋㅋ! 다음 이슈에서 고것도 연결할게용 ⋯
> [feat/#35] 필터 뷰 버튼 구현

- Roomie/Roomie/Global/Components/DatePickerView.swift
- Roomie/Roomie/Global/Extensions/String+.swift
- Roomie/Roomie/Presentation/MapFilter/View/FilterPeriodView.swift
- Roomie/Roomie/Presentation/MapFilter/ViewController/MapFilterViewController.swift
- Roomie/Roomie/Presentation/MapFilter/ViewModel/MapFilterViewModel.swift
- Connected: #39 
- 데이트포맷 함수를 외부에서 접근하기 위해 String 익스텐션으로 분리했어요.
- 승원이가 만들어준 끝내주는 델리게이트로 데이트피커 로직을 연결했어요.
- 화면 연결을 했습니다 ⋯
| 필터 뷰 | <img src = "https://github.com/user-attachments/assets/946464c9-1bee-44cb-ae34-161d8c257da4" width ="250"> | <img src = "https://github.com/user-attachments/assets/aaf0ab94-3323-4635-98ca-bea43d66cf35" width ="250"> |
API 호출을 위해 MapViewModel로 데이터 전달을 해야하는데, 
이 부분은 DTO 구현 이후 진행하는 게 좋을 것 같아서 TODO 주석만 남겨뒀어요!
> [feat/#39] 필터 뷰 UI 완성

- Roomie/Roomie/Global/Components/MoodButtonView.swift
- Roomie/Roomie/Presentation/Home/ViewController/HomeViewController.swift
- Roomie/Roomie/Presentation/MyPage/ViewController/MyPageViewController.swift
- Connected: #57 
- myPage, wishList를 연결하였습니다.
| 마이페이지 | <img src = "https://github.com/user-attachments/assets/a6904c2d-3bd6-48d4-a79d-3999424d3cfd" width ="250"> | <img src = "https://github.com/user-attachments/assets/968af1c2-1dc1-43b6-adaa-5d235731f139" width ="250"> |
연결 완 ~ 기분 굿 ~~
> [chore/#57] myPage, wishList 연결

- Roomie/Roomie/Global/Enums/Gradient.swift
- Roomie/Roomie/Global/Extensions/CAGradientLayer+.swift
- Roomie/Roomie/Global/Extensions/UIColor+.swift
- Roomie/Roomie/Global/Extensions/UIView+.swift
- Roomie/Roomie/Presentation/Home/View/HomeView.swift
- Roomie/Roomie/Presentation/Home/ViewController/HomeViewController.swift
- Roomie/Roomie/Presentation/MoodList/Model/MoodListModel.swift
- Roomie/Roomie/Presentation/MoodList/View/MoodListCollectionHeaderView.swift
- Roomie/Roomie/Presentation/MoodList/ViewController/MoodListViewController.swift
- Connected: #43 
- HomeView, MoodListView 배경에 그라데이션을 주었습니다.
| 홈뷰 | <img src = "https://github.com/user-attachments/assets/05863696-b351-4170-b5cd-33721ca910f9" width ="250"> | <img src = "https://github.com/user-attachments/assets/f0e1ef9c-a82e-43ce-aff3-b970ab0678ae" width ="250"> |
| 분위기리스트뷰 | <img src = "https://github.com/user-attachments/assets/29442a18-a5b2-44f6-bf3b-b3785e865778" width ="250"> | <img src = "https://github.com/user-attachments/assets/2a23e410-7d3f-4696-b838-a7690a99a778" width ="250"> |
그라데이션 넣으니까 너무 아름다워요 ~~~~ 개굿
> [chore/#43] 그라데이션 및 homeViewUI userName 수정

- Roomie/Roomie/Global/Resource/Colors.xcassets/transparent/transp_gray11_80.colorset/Contents.json
- Roomie/Roomie/Global/Utils/Toast.swift
- Connected: #18
- 디자인 명세에 맞게 토스트 뷰 유틸 코드를 구현했어요!
더 쓸 말이 없넹 ⋯
> [feat/#18] 토스트 유틸 코드 구현

- Roomie/Roomie/Global/Components/CheckIconLabel.swift
- Roomie/Roomie/Global/Components/GroundRuleLabel.swift
- Roomie/Roomie/Global/Components/HouseInfoIconLabel.swift
- Roomie/Roomie/Global/Components/MoodTagView.swift
- Roomie/Roomie/Global/Enums/MoodType.swift
- Roomie/Roomie/Presentation/HouseDetail/Helper/HouseDetailLayoutHelper.swift
- Roomie/Roomie/Presentation/HouseDetail/View/Cell/HouseDetailHeaderView.swift
- Roomie/Roomie/Presentation/HouseDetail/View/Cell/RoomMoodCell.swift
- Roomie/Roomie/Presentation/HouseDetail/View/HouseDetailView.swift
- Roomie/Roomie/Presentation/HouseDetail/ViewController/HouseDetailViewController.swift
- Roomie/Roomie/Presentation/HouseDetail/ViewModel/HouseDetailViewModel.swift
- Connected: #61  
- `HouseDetail` 에 section 3 (RoomMood) UI를 구현했습니다.
- 방 분위기, 그라운드룰 개수에 따라 Cell 높이를 동적으로 변하게 구현하였습니다.
| section3 UI | <img src = "https://github.com/user-attachments/assets/d1682199-2bbe-4611-b7fe-548988b21e5d" width ="250"> | <img src = "https://github.com/user-attachments/assets/4dad41a7-6121-40dd-9dfa-a966ea255981" width ="250"> |
- 상세 페이지 방 분위기 태그에서 메인 분위기 외의 분위기 태그의 색상이 달라져야하더라고요
- 현수가 만들 놓은 `MoodType` 타입의 `title` 활용하면 쉽게 처리할 수 있을 거 같아서 
- 아래처럼 `MoodType`에 `CaseIterable`프로토콜을 채택하였습니다.
- 열거형 타입을 배열처럼 다루기 위함이죠!
<details>
<summary>MoodType.swift</summary>
```swift
enum MoodType: CaseIterable {
case calm
case lively
case neat
// ...
```
</details>
</br>
- 그리고 컴포넌트 …
> [feat/#61] HouseDetail Section3(RoomMood) UI 구현

- Roomie/Roomie/Presentation/Home/ViewController/HomeViewController.swift
- Roomie/Roomie/Presentation/HouseDetail/Component/HouseMoodTagView.swift
- Roomie/Roomie/Presentation/HouseDetail/Helper/HouseDetailLayoutHelper.swift
- Roomie/Roomie/Presentation/HouseDetail/View/HouseDetailView.swift
- Roomie/Roomie/Presentation/HouseDetail/ViewController/HouseDetailViewController.swift
- Connected: #82 
- Compositional Layout -> ScrollView + UITableView로 리팩토링 진행하는 중입니다!
| section1, 2, 3 | <img src = "https://github.com/user-attachments/assets/76f4f59c-675c-463f-8675-4ca69795c17e" width ="250"> | <img src = "https://github.com/user-attachments/assets/beb04a51-4df4-4e51-b14a-c5a8e919a3ab" width ="250"> |
- 지금 주석이 좀 많은데 리팩토링 끝나고 다 깔끔하게 지워놓을게요 ㅎ 빠르게 어프룹 부탁드립니다!
- 네비바 관련 이슈도 뷰 옮기고 수정할게요!
> [refactor/#82] 매물 상세 페이지 section 1, 2, 3 리팩토링

- Roomie/Roomie/Presentation/HouseDetail/Component/HouseInfoIconLabel.swift
- Roomie/Roomie/Presentation/HouseDetail/Component/RoomTourButton.swift
- Roomie/Roomie/Presentation/HouseDetail/View/HouseDetailSheetView.swift
- Roomie/Roomie/Presentation/HouseDetail/View/HouseDetailView.swift
- Roomie/Roomie/Presentation/HouseDetail/ViewController/HouseDetailSheetViewController.swift
- Roomie/Roomie/Presentation/HouseDetail/ViewController/HouseDetailViewController.swift
- Roomie/Roomie/Presentation/HouseDetail/ViewModel/HouseDetailViewModel.swift
- Connected: #96 
- 매물 상세 페이지에 bottomSheet을 구현했습니다.
| UI | <img src = "https://github.com/user-attachments/assets/c139a70b-0858-4c8c-9bfb-876d194e4c9c" width ="250"> | <img src = "https://github.com/user-attachments/assets/31f68f9d-62cb-448e-a566-bda4b866b570" width ="250"> |
- 기본적으로 방은 룸A ~ F 로 네이밍 되기 때문에 각각 버튼에 tag를 달아서 쉽게 관리할 수 있게 구현했어요
<details>
<summary>HouseDetailSheetView.swift</summary>
```swift
private extension HouseDetailSheetView {
func setButtons() {
buttons.append(roomATourButton)
roomATourButton.tag = 0
buttons.append(roomBTourButton)
roomBTourButton.tag = 1
buttons.append(roomCTourButton)
roomCTourButton.tag = 2
buttons.append(roomDTourButton)
roomDTourButton.tag = 3 …
```
> [feat/#96] 매물 상세 페이지 Bottom Sheet UI 구현

- Roomie/Roomie/Network/DTO/Houses/MoodListRequestDTO.swift
- Roomie/Roomie/Network/DTO/Houses/MoodListResponseDTO.swift
- Connected: #100 
- 분위기별 리스트 DTO를 구현했습니다.
> [feat/#104] 분위기별 리스트 DTO 구현

- Roomie/Roomie/Global/Components/VersionFooterView.swift
- Roomie/Roomie/Network/DTO/BaseDTO/BaseResponseBody.swift
- Roomie/Roomie/Network/Service/HomeService.swift
- Roomie/Roomie/Network/Service/HousesService.swift
- Roomie/Roomie/Network/Service/MapsService.swift
- Roomie/Roomie/Network/Service/MyPageService.swift
- Roomie/Roomie/Network/TargetType/HomeTargetType.swift
- Roomie/Roomie/Network/TargetType/HousesTargetType.swift
- Roomie/Roomie/Network/TargetType/MapsTargetType.swift
- Roomie/Roomie/Network/TargetType/MyPageTargetType.swift
- Roomie/Roomie/Presentation/Core/MainTabBarController.swift
- Roomie/Roomie/Presentation/Home/ServiceProtocol/HomeServiceProtocol.swift
- Roomie/Roomie/Presentation/HouseDetail/ServiceProtocol/HouseDetailServiceProtocol.swift
- Roomie/Roomie/Presentation/Map/ServiceProtocol/MapServiceProtocol.swift
- Roomie/Roomie/Presentation/MoodList/ServiceProtocol/MoodListServiceProtocol.swift
- Roomie/Roomie/Presentation/WishList/ServiceProtocol/WishListServiceProtocol.swift
- Connected: #119
- 찜 API 구현을 위해 뷰에 맞게 타겟타입을 분리했어요.
- 서버가 일어나면 찜을 붙이실 여러분을 위해 TODO 주석도 남겨놨어요잉!
얘둘아 사랑해 😚
> [fix/#119] 타겟타입 분리

- Roomie/Roomie/Presentation/Home/View/HomeView.swift
- Roomie/Roomie/Presentation/Home/ViewController/HomeViewController.swift
- Connected: #81 
- 홈 뷰 스크롤 시 네비바 색상 변경을 구현했습니다.
- 홈 뷰 스크롤 시 바운싱 될 때 배경 색상 변경을 구현했습니다.
| 홈뷰 | <img src = "https://github.com/user-attachments/assets/dd4c414d-d78a-4772-b833-af3e4518ef84" width ="250"> | <img src = "https://github.com/user-attachments/assets/a68c700c-df58-4933-b961-8a741da992ec" width ="250"> |
- 커스텀 네비바를 사용해서 barAppearance로 배경 색상을 변경하고 있어 이를 전역변수로 뺀 후 enum으로 정의한 상태를 didSet에서 담고 있다가 상태에 따라 색상이 변경되도록 함수를 구현했습니다.
<details>
<summary>HomeViewController</summary>
```swift
func setHomeNavigationBarStatus() {
switch homeNavigationBarStatus {
case .white:
barAppearance.backgroundColor = .grayscale1
case .purple:
barAppearance.backgroundColor = .primaryLight4
} …
```
> [feat/#81] home view UI detail 잡기

- Roomie/Roomie/Global/Components/RoomieIconButton.swift
- Roomie/Roomie/Presentation/Map/View/MapView.swift
- Roomie/Roomie/Presentation/Map/ViewController/MapListSheetViewController.swift
- Roomie/Roomie/Presentation/Map/ViewController/MapViewController.swift
- Roomie/Roomie/Presentation/Map/ViewModel/MapViewModel.swift
- Connected: #125
- 카메라 이동 및 줌과 같은 세부 사항을 수정했어요.
- 디자인 단 요청에 따라 장소 초기화 기능을 추가했어요.
|    구현 내용    |   iPhone 13 mini   |
| :-------------: | :----------: |
| 지도 뷰 | <img src = "https://github.com/user-attachments/assets/16218d7d-473c-4c6d-afc2-cbbde33ff56a" width ="250"> | 
개힘듦 ㅋㅋ
> [feat/#125] 지도 뷰 디테일 구현 및 장소 초기화 기능 추가

- Roomie/Roomie/Global/Components/HouseListCollectionViewCell.swift
- Roomie/Roomie/Global/Utils/Toast.swift
- Roomie/Roomie/Network/DTO/Houses/MoodListResponseDTO.swift
- Roomie/Roomie/Network/DTO/Houses/PinWishResponseDTO.swift
- Roomie/Roomie/Network/DTO/Houses/PinnedResponseDTO.swift
- Roomie/Roomie/Network/DTO/Houses/WishListResponseDTO.swift
- Roomie/Roomie/Network/DTO/Maps/MapResponseDTO.swift
- Roomie/Roomie/Network/DTO/Users/HomeResponseDTO.swift
- Roomie/Roomie/Network/Service/HomeService.swift
- Roomie/Roomie/Network/Service/HousesService.swift
- Roomie/Roomie/Presentation/Home/ServiceProtocol/HomeServiceProtocol.swift
- Roomie/Roomie/Presentation/Home/ViewController/HomeViewController.swift
- Roomie/Roomie/Presentation/Home/ViewModel/HomeViewModel.swift
- Roomie/Roomie/Presentation/MoodList/ServiceProtocol/MoodListServiceProtocol.swift
- Roomie/Roomie/Presentation/WishList/ServiceProtocol/WishListServiceProtocol.swift
- Roomie/Roomie/Presentation/WishList/ViewController/WishListViewController.swift
- Roomie/Roomie/Presentation/WishList/ViewModel/WishListViewModel.swift
- Connected: #123 
- 찜 버튼 API를 홈 뷰와 찜 리스트 뷰에 붙였습니다.
- 셀 안에 존재하는 버튼을 누르면 해당 셀의 houseID에 해당되는 매물의 isPinned값이 변경되도록 하고자 houseID를 passthroughsubject로 선언하여 viewController와 viewModel 사이 houseID전달을 했습니다.
- viewModel에서 houseID를 받아 해당 ID의 매물의 isPinned값을 업데이트 하도록 하였습니다.
- viewModel에서 houseID와 isPinned값을 passthroughsubject로 선언하여 output으로 viewController로 내보냈습니다.
- viewController에서는 houseID와 isPinned값을 받아 해당되는 cell만 업데이트하여 UI를 그리도록 구현했습니다.
- isPinned == false일 경우 토스트뷰가 나타나도록 구현했습니다.
| 찜 버튼 | <img src = "https://github.com/user-attachments/assets/c5349e20-5bce-4a96-ab2f-200661416559" width ="250"> | <img src = "https://github.com/user-attachments/assets/98adb4ee-fd8f-4614-a4ce-3626e2977cc3" width …
> [feat/#123] wishList, homeView 찜 버튼 API 구현

- Roomie/Roomie/Presentation/Home/ViewController/HomeViewController.swift
- Roomie/Roomie/Presentation/Home/ViewModel/HomeViewModel.swift
- Roomie/Roomie/Presentation/WishList/View/WishListView.swift
- Roomie/Roomie/Presentation/WishList/ViewController/WishListViewController.swift
- Roomie/Roomie/Presentation/WishList/ViewModel/WishListViewModel.swift
- Connected: #136 
- 홈뷰, 찜리스트뷰 상세매물페이지 연결 코드리뷰 반영 수정
코드리뷰 반영 수정 못하고 머지해서 바로 이슈파서 올립니더!!!!!
아요들아 미안
> [chore/#136] 홈뷰, 찜리스트뷰 상세매물페이지 연결 코드리뷰 반영 수정

- Roomie/Roomie/Global/Components/DatePickerView.swift
- Roomie/Roomie/Network/DTO/Houses/TourRequestDTO.swift
- Roomie/Roomie/Network/DTO/Houses/TourResponseDTO.swift
- Roomie/Roomie/Network/Service/HousesService.swift
- Roomie/Roomie/Network/TargetType/HousesTargetType.swift
- Roomie/Roomie/Network/TargetType/MapsTargetType.swift
- Roomie/Roomie/Presentation/HouseDetail/Component/RoomFacilityExpandView.swift
- Roomie/Roomie/Presentation/HouseDetail/Model/SelectedRoomInfo.swift
- Roomie/Roomie/Presentation/HouseDetail/ServiceProtocol/HouseDetailServiceProtocol.swift
- Roomie/Roomie/Presentation/HouseDetail/View/Cell/RoomStatusTableViewCell.swift
- Roomie/Roomie/Presentation/HouseDetail/View/HouseDetailSheetView.swift
- Roomie/Roomie/Presentation/HouseDetail/View/HouseDetailView.swift
- Roomie/Roomie/Presentation/HouseDetail/ViewController/HouseAllPhotoViewController.swift
- Roomie/Roomie/Presentation/HouseDetail/ViewController/HouseDetailSheetViewController.swift
- Roomie/Roomie/Presentation/HouseDetail/ViewController/HouseDetailViewController.swift
- Roomie/Roomie/Presentation/HouseDetail/ViewController/HouseSinglePhotoViewController.swift
- Roomie/Roomie/Presentation/HouseDetail/ViewModel/HouseDetailViewModel.swift
- Roomie/Roomie/Presentation/Tour/Component/TourTextView.swift
- Roomie/Roomie/Presentation/Tour/Model/TourRequestModelBuilder.swift
- Roomie/Roomie/Presentation/Tour/View/TourUserView.swift
- Roomie/Roomie/Presentation/Tour/ViewController/TourCheckViewController.swift
- Roomie/Roomie/Presentation/Tour/ViewController/TourCompleteViewController.swift
- Roomie/Roomie/Presentation/Tour/ViewController/TourDateViewController.swift
- Roomie/Roomie/Presentation/Tour/ViewController/TourUserViewController.swift
- Roomie/Roomie/Presentation/Tour/ViewModel/TourCheckViewModel.swift
- Roomie/Roomie/Presentation/Tour/ViewModel/TourDateViewModel.swift
- Roomie/Roomie/Presentation/Tour/ViewModel/TourUserViewModel.swift
- Connected: #133
- 투어플로우 API를 연결했어요!
- 그리고 이후에 다른 방 보러가기, 홈 화면으로 이동하는 걸 구현했어요
|    구현 내용    |   iPhone 13 mini   | 
| :-------------: | :----------: |
| 투어 신청 | <img src = "https://github.com/user-attachments/assets/31582fcd-ff17-45c9-96a5-4ff04406c4e1" width ="250"> |]
- 정신이 지금 혼미해서 개행같은 거나 주석이 좀 많을 거 같아요
- 꼼꼼하게 봐주세면 감사하겠습니다. ㅋㅋ
> [feat/#133] 투어 신청 플로우 API 연동, 이후 네비게이션 연결

- Roomie/Roomie/Presentation/Home/Component/AppleLoverClub.swift
- Roomie/Roomie/Presentation/Home/ViewController/APPLELOVERCLUBViewController.swift
- Roomie/Roomie/Presentation/Home/ViewController/HomeViewController.swift
- Connected: #132 
- 홈 뷰에서 연결되는 웹뷰를 작업했습니다.
| 홈뷰 웹뷰 | <img src = "https://github.com/user-attachments/assets/7afc8fd6-a0f3-4ce2-8e35-014ad412b275" width ="250"> | <img src = "https://github.com/user-attachments/assets/195b84b5-4b3e-4725-8515-2c05a3358963" width ="250"> |
- https://apple-apeach.tistory.com/15
> [feat/#132] 홈뷰 웹뷰 연결

- Roomie/Roomie/Presentation/MoodList/ViewController/MoodListViewController.swift
- Roomie/Roomie/Presentation/Tour/ViewController/TourCompleteViewController.swift
- Roomie/Roomie/Presentation/WishList/ViewController/WishListViewController.swift
- Connected: #149 
- 투어 신청 플로우 이후 네비바 제스처 오류 수정했습니다.
- 홈 뷰 네비게이션 바 배경색 자잘한 오류 수정 중인데, 아직 해결은 못 했어욤
> [fix] 투어 신청 플로우 후 네비게이션 제스처 오류 수정

- Roomie/Roomie/Presentation/HouseDetail/ViewController/HouseDetailViewController.swift
- Roomie/Roomie/Presentation/HouseDetail/ViewController/HouseDetailWebViewController.swift
- Connected: #151 
- 하우스디테일뷰에서 연결되는 카카오톡 채널 웹뷰를 구현했습니다.
| 카카오톡 채널 웹뷰 | <img src = "https://github.com/user-attachments/assets/cbc3f988-5a9c-4ff9-801a-efd51ea54486" width ="250"> | <img src = "https://github.com/user-attachments/assets/dd32f8e2-a272-44ba-a25b-f5b02a6f407f" width ="250"> |
진짜 끗 아요들아 수고 많앗두앙
> [feat/#151] HouseDetailView 카카오톡 웹 뷰 연결

- Roomie/Roomie/Network/Service/HousesService.swift
- Roomie/Roomie/Presentation/HouseDetail/Component/RoomFacilityExpandView.swift
- Roomie/Roomie/Presentation/HouseDetail/View/Cell/RoomStatusTableViewCell.swift
- Roomie/Roomie/Presentation/HouseDetail/View/Cell/RoommateNotFoundTableViewCell.swift
- Roomie/Roomie/Presentation/HouseDetail/View/Cell/RoommateTableViewCell.swift
- Roomie/Roomie/Presentation/HouseDetail/View/HouseAllPhotoView.swift
- Roomie/Roomie/Presentation/HouseDetail/View/HouseDetailView.swift
- Roomie/Roomie/Presentation/HouseDetail/ViewController/HouseDetailViewController.swift
- Roomie/Roomie/Presentation/HouseDetail/ViewController/HouseDetailWebViewController.swift
- Connected: #152 
- 152번 브랜치를 실수로 main에 머지해서 되돌리고 다시 머지하겠습니닷..!
> [hotfix] 152번 브랜치 -> develop

- Roomie/Roomie/Network/DTO/Houses/HouseDetailResponseDTO.swift
- Roomie/Roomie/Network/Service/HousesService.swift
- Roomie/Roomie/Presentation/HouseDetail/Model/RoomInfo.swift
- Roomie/Roomie/Presentation/HouseDetail/ViewController/HouseDetailViewController.swift
- Roomie/Roomie/Presentation/HouseDetail/ViewModel/HouseDetailViewModel.swift
- Connected: #192 
- 매물상세페이지 바뀐 DTO로 수정하였습니다.
- 매물상세 -> 매물상세이미지 MockService에서 실제 Service로 갈아끼웠습니다
- 잘 돌아가는 거 확인했습니다!
- 그 투어신청에서 텍스트 필드 모두 입력 중일 때 보라색으로 border표시되는데 요거 확인 부탁한 거 맞나요? @mmaybei
> [refactor/#192] 매물상세페이지 DTO수정
